export const environment = {
    production: true,
    server: 'http://localhost:4200/',
    utagInfo: {
        oralSystem: {
            page_category: 'home | drglister',  
            page_name: 'home',
            page_section: 'home',
            page_subCategory: 'home',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        oralSystemAnimation: {
            page_category: 'Oral System | drglister',  
            page_name: 'Oral System',
            page_section: 'Oral System',
            page_subCategory: 'Oral System',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        oralSystemStep1: {
            page_category: 'Oral System | drglister',  
            page_name: 'Oral System',
            page_section: 'Step 1',
            page_subCategory: 'Oral System',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        oralSystemStep2: {
            page_category: 'Oral System | drglister',  
            page_name: 'Oral System',
            page_section: 'Step 2',
            page_subCategory: 'Oral System',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        oralSystemStep3: {
            page_category: 'Oral System | drglister',  
            page_name: 'Oral System',
            page_section: 'Step 3',
            page_subCategory: 'Oral System',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        oralSystemStep4: {
            page_category: 'Oral System | drglister',  
            page_name: 'Oral System',
            page_section: 'Refresh',
            page_subCategory: 'Oral System',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        oralSystemAllSteps: {
            page_category: 'Oral System | drglister',  
            page_name: 'home',
            page_section: 'home',
            page_subCategory: 'home',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        buyOralSystem: {
            page_category: 'Shop | drglister',  
            page_name: 'Shop',
            page_section: 'Shop',
            page_subCategory: 'Shop',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        buyProduct1: {
            page_category: 'Shop | drglister',  
            page_name: 'Shop',
            page_section: 'Shop',
            page_subCategory: 'Shop',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        buyProduct2: {
            page_category: 'Shop | drglister',  
            page_name: 'Shop',
            page_section: 'Shop',
            page_subCategory: 'Shop',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        buyProduct3: {
            page_category: 'Shop | drglister',  
            page_name: 'Shop',
            page_section: 'Shop',
            page_subCategory: 'Shop',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        buyProduct4: {
            page_category: 'Shop | drglister',  
            page_name: 'Shop',
            page_section: 'Shop',
            page_subCategory: 'Shop',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        learn: {
            page_category: 'Oral System | drglister',  
            page_name: 'home',
            page_section: 'home',
            page_subCategory: 'home',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        traceability: {
            page_category: 'Tracebility | drglister',  
            page_name: 'Tracebility',
            page_section: 'Tracebility',
            page_subCategory: 'Tracebility',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        drGlister: {
            page_category: 'Dr. Glister | drglister',  
            page_name: 'Dr. Glister',
            page_section: 'Dr. Glister',
            page_subCategory: 'Dr. Glister',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        drGlisterTips: {
            page_category: 'Dr. Glister | drglister',  
            page_name: 'Dr. Glister',
            page_section: 'Dr. Glister',
            page_subCategory: 'Dr. Glister',
            //site_country: '',
            //site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
    }
};
